name: Daily Commit Workflow

on:
  schedule:
    - cron: "0 6 * * *"  # Runs at 06:00 UTC daily
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Step by 23f2000137@ds.study.iitm.ac.in
        run: |
          echo "Run timestamp: $(date -u)" > commit.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add commit.txt
          git commit -m "Daily commit at $(date -u)"
          git push
